// Per-module structured logger for the core FE.
//
// Each module repository builds one logger with `createModuleLogger("catalog")`
// and uses it to wrap apiClient calls. Every log line carries the module name,
// the operation, an autogenerated requestId (also sent to the backend as the
// `X-Request-ID` header), and the elapsed time so logs across modules are
// uniformly filterable.

import { ValidationError } from "~/shared/domain/errors/validation-error";
import { NetworkError } from "~/shared/domain/errors/network-error";

export type ModuleLogger = ReturnType<typeof createModuleLogger>;

export type LogContext = Record<string, unknown>;

type ModuleLogLevel = "debug" | "info" | "warn" | "error";

const ENABLED =
  typeof import.meta !== "undefined" &&
  (import.meta.env?.MODE !== "production" || import.meta.env?.VITE_LOG_HTTP === "true");

function emit(level: ModuleLogLevel, module: string, event: string, context: LogContext): void {
  if (!ENABLED) {
    return;
  }
  const line = {
    level,
    module,
    event,
    ...context,
  };
  switch (level) {
    case "error":
      console.error(line);
      return;
    case "warn":
      console.warn(line);
      return;
    case "debug":
      console.debug(line);
      return;
    default:
      console.info(line);
  }
}

function createRequestId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  return `r${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

export function createModuleLogger(module: string) {
  return {
    debug(event: string, context: LogContext = {}): void {
      emit("debug", module, event, context);
    },
    info(event: string, context: LogContext = {}): void {
      emit("info", module, event, context);
    },
    warn(event: string, context: LogContext = {}): void {
      emit("warn", module, event, context);
    },
    error(event: string, context: LogContext = {}): void {
      emit("error", module, event, context);
    },

    /**
     * Wrap a repository operation that calls the backend. Logs:
     *  - `op_started` with operation + requestId
     *  - `op_succeeded` with elapsedMs on success
     *  - `op_failed` with elapsedMs + classified error on failure
     *
     * The returned `requestId` should be threaded into the apiClient call via
     * the `X-Request-ID` header so the backend per-module middleware can
     * correlate the same request id end-to-end.
     */
    async trace<T>(
      operation: string,
      run: (ctx: { requestId: string }) => Promise<T>,
      context: LogContext = {},
    ): Promise<T> {
      const requestId = createRequestId();
      const startedAt = typeof performance !== "undefined" ? performance.now() : Date.now();
      emit("info", module, "op_started", { operation, requestId, ...context });

      try {
        const result = await run({ requestId });
        const elapsedMs = Math.round(
          (typeof performance !== "undefined" ? performance.now() : Date.now()) - startedAt,
        );
        emit("info", module, "op_succeeded", {
          operation,
          requestId,
          elapsedMs,
          ...context,
        });
        return result;
      } catch (error) {
        const elapsedMs = Math.round(
          (typeof performance !== "undefined" ? performance.now() : Date.now()) - startedAt,
        );
        emit("warn", module, "op_failed", {
          operation,
          requestId,
          elapsedMs,
          ...classifyError(error),
          ...context,
        });
        throw error;
      }
    },
  };
}

function classifyError(error: unknown): LogContext {
  if (error instanceof ValidationError) {
    return {
      errorKind: "validation",
      message: error.message,
      statusCode: error.statusCode,
    };
  }
  if (error instanceof NetworkError) {
    return {
      errorKind: "network",
      message: error.message,
      statusCode: error.statusCode,
    };
  }
  if (error instanceof Error) {
    return { errorKind: "unknown", message: error.message };
  }
  return { errorKind: "unknown", message: String(error) };
}
